DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'eirservice') THEN
        CREATE ROLE eirservice LOGIN PASSWORD 'EirService-dev-2026!';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'mimirservice') THEN
        CREATE ROLE mimirservice LOGIN PASSWORD 'MimirService-dev-2026!';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'gnaservice') THEN
        CREATE ROLE gnaservice LOGIN PASSWORD 'GnaService-dev-2026!';
    END IF;
END
$$;

SELECT 'CREATE DATABASE eir'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'eir')\gexec
SELECT 'CREATE DATABASE mimir'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mimir')\gexec
SELECT 'CREATE DATABASE gna'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'gna')\gexec

\connect eir
GRANT CONNECT ON DATABASE eir TO eirservice;
GRANT USAGE ON SCHEMA public TO eirservice;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO eirservice;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO eirservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eirservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO eirservice;

\connect mimir
GRANT CONNECT ON DATABASE mimir TO mimirservice;
GRANT USAGE ON SCHEMA public TO mimirservice;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mimirservice;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO mimirservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mimirservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mimirservice;

\connect gna
GRANT CONNECT ON DATABASE gna TO gnaservice;
GRANT USAGE ON SCHEMA public TO gnaservice;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gnaservice;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO gnaservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gnaservice;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO gnaservice;
